enum ScreenName {
  TEST_CONFIG = 'TEST_CONFIG',
  WALLET = 'WALLET',
  TRANSACTION_ICONS = 'TRANSACTION_ICONS',
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  SELECT_CATEGORY = 'SELECT_CATEGORY',
  ADD_CATEGORY = 'ADD_CATEGORY',
  NOTE = 'NOTE',
  SELECT_WALLET = 'SELECT_WALLET',
  ADD_WALLET = 'ADD_WALLET',
}

export {ScreenName};
