enum ScreenName {
  TEST_CONFIG = 'TEST_CONFIG',
  WALLET = 'WALLET',
  TRANSACTION_ICONS = 'TRANSACTION_ICONS',
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  SELECT_CATEGORY = 'SELECT_CATEGORY',
}

export {ScreenName};
